### ISSUE TITLE
7z (PS1 ReDump): [SEVERE] Other Exception when listing

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#137]
In my source I have mixed archives: `7z`, `rar`, `zip`.
They're all fine, no corruptions.

The problem occurs only when using 7z.

After _Scanning_ I got this (`JRM.0.log`):
```
[SEVERE] Other Exception when listing
java.nio.file.ProviderNotFoundException: Provider not found
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:423)
	at jrm.profile.scan.DirScan.getPath(DirScan.java:1386)
	at jrm.profile.scan.DirScan.updateEntryCHD(DirScan.java:1317)
	at jrm.profile.scan.DirScan.updateEntry(DirScan.java:1228)
	at jrm.profile.scan.DirScan.updateEntry(DirScan.java:1211)
	at jrm.profile.scan.DirScan.scanFake(DirScan.java:717)
	at jrm.profile.scan.DirScan.scanContainer(DirScan.java:448)
	at jrm.profile.scan.DirScan.lambda$new$1(DirScan.java:385)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Despite that, it completes and I can take the next step to proceed fixing my PS1 discs, **but** it then fails (with and without MultiThreading).
```
[SEVERE] IOException when scanning
net.sf.sevenzipjbinding.SevenZipException: Archive file can't be opened with any of the registered codecs
	at net.sf.sevenzipjbinding.SevenZip.nativeOpenArchive(Native Method)
	at net.sf.sevenzipjbinding.SevenZip.callNativeOpenArchive(SevenZip.java:904)
	at net.sf.sevenzipjbinding.SevenZip.openInArchive(SevenZip.java:794)
	at jrm.compressors.NArchive.<init>(NArchive.java:147)
	at jrm.compressors.SevenZipNArchive.<init>(SevenZipNArchive.java:45)
	at jrm.compressors.SevenZipArchive.<init>(SevenZipArchive.java:74)
	at jrm.compressors.SevenZipArchive.<init>(SevenZipArchive.java:61)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.getArchive(DirScan.java:976)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.getNInterface(DirScan.java:987)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.updateEntries7ZipJBindingMethod(DirScan.java:1016)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.updateEntries(DirScan.java:999)
	at jrm.profile.scan.DirScan.scanContainer(DirScan.java:437)
	at jrm.profile.scan.DirScan.lambda$new$1(DirScan.java:385)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[SEVERE] IOException when scanning
net.sf.sevenzipjbinding.SevenZipException: Archive file can't be opened with any of the registered codecs
	at net.sf.sevenzipjbinding.SevenZip.nativeOpenArchive(Native Method)
	at net.sf.sevenzipjbinding.SevenZip.callNativeOpenArchive(SevenZip.java:904)
	at net.sf.sevenzipjbinding.SevenZip.openInArchive(SevenZip.java:794)
	at jrm.compressors.NArchive.<init>(NArchive.java:147)
	at jrm.compressors.SevenZipNArchive.<init>(SevenZipNArchive.java:45)
	at jrm.compressors.SevenZipArchive.<init>(SevenZipArchive.java:74)
	at jrm.compressors.SevenZipArchive.<init>(SevenZipArchive.java:61)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.getArchive(DirScan.java:976)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.getNInterface(DirScan.java:987)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.updateEntries7ZipJBindingMethod(DirScan.java:1016)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.updateEntries(DirScan.java:999)
	at jrm.profile.scan.DirScan.scanContainer(DirScan.java:437)
	at jrm.profile.scan.DirScan.lambda$new$1(DirScan.java:385)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[SEVERE] IOException when scanning
net.sf.sevenzipjbinding.SevenZipException: Archive file can't be opened with any of the registered codecs
	at net.sf.sevenzipjbinding.SevenZip.nativeOpenArchive(Native Method)
	at net.sf.sevenzipjbinding.SevenZip.callNativeOpenArchive(SevenZip.java:904)
	at net.sf.sevenzipjbinding.SevenZip.openInArchive(SevenZip.java:794)
	at jrm.compressors.NArchive.<init>(NArchive.java:147)
	at jrm.compressors.SevenZipNArchive.<init>(SevenZipNArchive.java:45)
	at jrm.compressors.SevenZipArchive.<init>(SevenZipArchive.java:74)
	at jrm.compressors.SevenZipArchive.<init>(SevenZipArchive.java:61)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.getArchive(DirScan.java:976)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.getNInterface(DirScan.java:987)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.updateEntries7ZipJBindingMethod(DirScan.java:1016)
	at jrm.profile.scan.DirScan$SevenZUpdateEntries.updateEntries(DirScan.java:999)
	at jrm.profile.scan.DirScan.scanContainer(DirScan.java:437)
	at jrm.profile.scan.DirScan.lambda$new$1(DirScan.java:385)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[SEVERE] add from Driver (Italy).zip@/Driver (Italy).bin to Driver (Italy).7z@Driver (Italy).bin failed
java.io.IOException: Spazio esaurito sul device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1310)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1043)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:952)
	at jrm.compressors.NArchive.addStdIn(NArchive.java:375)
	at jrm.compressors.SevenZipNArchive.addStdIn(SevenZipNArchive.java:30)
	at jrm.compressors.SevenZipArchive.addStdIn(SevenZipArchive.java:215)
	at jrm.profile.fix.actions.AddEntry.zip2Archive(AddEntry.java:456)
	at jrm.profile.fix.actions.AddEntry.doAction(AddEntry.java:420)
	at jrm.profile.fix.actions.ContainerAction.archiveAction(ContainerAction.java:157)
	at jrm.profile.fix.actions.CreateContainer.createSevenZip(CreateContainer.java:153)
	at jrm.profile.fix.actions.CreateContainer.doAction(CreateContainer.java:108)
	at jrm.profile.fix.Fix.doAction(Fix.java:118)
	at jrm.profile.fix.Fix.lambda$new$2(Fix.java:81)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[SEVERE] action to Driver (Italy).7z@/Driver (Italy).bin failed
[WARNING] Action Create Container /somepath/dest/Driver (Italy).7z
	Add /somepath/source/Driver (Italy).zip::/Driver (Italy).cue to Driver (Italy).cue
	Add /somepath/source/Driver (Italy).zip::/Driver (Italy).bin to Driver (Italy).bin has failed, remaining actions processing will be cancelled
[SEVERE] add from Driver (Europe).zip@/Driver (Europe).bin to Driver (Europe).7z@Driver (Europe).bin failed
java.io.IOException: Spazio esaurito sul device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1310)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1043)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:952)
	at jrm.compressors.NArchive.addStdIn(NArchive.java:375)
	at jrm.compressors.SevenZipNArchive.addStdIn(SevenZipNArchive.java:30)
	at jrm.compressors.SevenZipArchive.addStdIn(SevenZipArchive.java:215)
	at jrm.profile.fix.actions.AddEntry.zip2Archive(AddEntry.java:456)
	at jrm.profile.fix.actions.AddEntry.doAction(AddEntry.java:420)
	at jrm.profile.fix.actions.ContainerAction.archiveAction(ContainerAction.java:157)
	at jrm.profile.fix.actions.CreateContainer.createSevenZip(CreateContainer.java:153)
	at jrm.profile.fix.actions.CreateContainer.doAction(CreateContainer.java:108)
	at jrm.profile.fix.Fix.doAction(Fix.java:118)
	at jrm.profile.fix.Fix.lambda$new$2(Fix.java:81)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[SEVERE] action to Driver (Europe).7z@/Driver (Europe).bin failed
[WARNING] Action Create Container /somepath/dest/Driver (Europe).7z
	Add /somepath/source/Driver (Europe).zip::/Driver (Europe).cue to Driver (Europe).cue
	Add /somepath/source/Driver (Europe).zip::/Driver (Europe).bin to Driver (Europe).bin has failed, remaining actions processing will be cancelled
[WARNING] Missed 16 actions
[WARNING] Missed 3 actions
[INFO] Fix total duration for Sony - PlayStation - Datfile (10619) (2021-11-05 22-46-57).dat : 00:00:08.056

```

DAT: http://redump.org/datfile/psx/

**Comment by optyfr** [comment]
```
[SEVERE] Other Exception when listing
java.nio.file.ProviderNotFoundException: Provider not found
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:423)
	at jrm.profile.scan.DirScan.getPath(DirScan.java:1386)
	at jrm.profile.scan.DirScan.updateEntryCHD(DirScan.java:1317)
```
Do you really have CHD in you dirs at this point ?
Is fake mode really intentional ?

**Comment by cinnamonmatexfce** [comment]
> 
> 
>  Is fake mode really intentional ?

???



> 
> 
> ```
> [SEVERE] Other Exception when listing
> java.nio.file.ProviderNotFoundException: Provider not found
> 	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:423)
> 	at jrm.profile.scan.DirScan.getPath(DirScan.java:1386)
> 	at jrm.profile.scan.DirScan.updateEntryCHD(DirScan.java:1317)
> ```
> 
> Do you really have CHD in you dirs at this point ?

Yes, I have one `chd` file.
I also select and check _Disks Dest._ (which has the same path for _Roms Dest._)
You mean I should only leave _Roms Dest._ alone?

**Comment by optyfr** [comment]
Disks dest is useless if identical to roms, but it is not the problem. Here it seems to find files ending with .chd
Fake mode is the « one file per archive mode » it seems activated but I doubt you need this for psx redump
All these exceptions seem strange to me

**Comment by cinnamonmatexfce** [comment]
> 
> 
>  Fake mode is the « one file per archive mode » it seems activated but I doubt you need this for psx redump 

No I'm not, I'm using FULL Non-Merged.


> 
> 
> Here it seems to find files ending with .chd 

WAIT... DAMN!!! SORRY!!!
I have one `chd` inside my source folder... My bad, I didn't noticed that... :/
Let me try deleting that damn one `chd` of hell... Sh*t!

**Comment by cinnamonmatexfce** [comment]
> ```
> [SEVERE] Other Exception when listing
> java.nio.file.ProviderNotFoundException: Provider not found
> 	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:423)
> 	at jrm.profile.scan.DirScan.getPath(DirScan.java:1386)
> 	at jrm.profile.scan.DirScan.updateEntryCHD(DirScan.java:1317)
> ```
> 
> Do you really have CHD in you dirs at this point ? Is fake mode really intentional ?

Deleting the one (and only) `chd` removed the error _[SEVERE] Other Exception when listing_.

But still remain all the other errors...

**Comment by cinnamonmatexfce** [comment]
Closing this, because this issue was started with another kind of problem (`chd`).
Re-opening (with different title and different target issue) as #138
