### ISSUE TITLE
7z (PS1 ReDump): java.io.IOException, nio.file.FileSystemException

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#138]
Re-opening from #137

```
[SEVERE] add from foo.zip@/foo (Track 10).bin to foo.7z@foo (Track 10).bin failed
java.io.IOException: Spazio esaurito sul device
	at java.base/java.io.FileOutputStream.writeBytes(Native Method)
	at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1310)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1043)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:952)
	at jrm.compressors.NArchive.addStdIn(NArchive.java:375)
	at jrm.compressors.SevenZipNArchive.addStdIn(SevenZipNArchive.java:30)
	at jrm.compressors.SevenZipArchive.addStdIn(SevenZipArchive.java:215)
	at jrm.profile.fix.actions.AddEntry.zip2Archive(AddEntry.java:456)
	at jrm.profile.fix.actions.AddEntry.doAction(AddEntry.java:420)
	at jrm.profile.fix.actions.ContainerAction.archiveAction(ContainerAction.java:157)
	at jrm.profile.fix.actions.CreateContainer.createSevenZip(CreateContainer.java:153)
	at jrm.profile.fix.actions.CreateContainer.doAction(CreateContainer.java:108)
	at jrm.profile.fix.Fix.doAction(Fix.java:118)
	at jrm.profile.fix.Fix.lambda$new$2(Fix.java:81)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
[SEVERE] add from foo.7z@foo.bin to foo.7z@foo.bin failed
java.nio.file.FileSystemException: /tmp/JRM15801415005895917723/foo.bin -> /tmp/JRM10273005425502751393/foo.bin: Spazio esaurito sul device
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:258)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:258)
	at java.base/java.nio.file.Files.copy(Files.java:1295)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:850)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:756)
	at jrm.compressors.NArchive.add(NArchive.java:363)
	at jrm.compressors.SevenZipNArchive.add(SevenZipNArchive.java:30)
	at jrm.compressors.SevenZipArchive.add(SevenZipArchive.java:201)
	at jrm.profile.fix.actions.AddEntry.default2Archive(AddEntry.java:437)
	at jrm.profile.fix.actions.AddEntry.doAction(AddEntry.java:422)
	at jrm.profile.fix.actions.ContainerAction.archiveAction(ContainerAction.java:157)
	at jrm.profile.fix.actions.CreateContainer.createSevenZip(CreateContainer.java:153)
	at jrm.profile.fix.actions.CreateContainer.doAction(CreateContainer.java:108)
	at jrm.profile.fix.Fix.doAction(Fix.java:118)
	at jrm.profile.fix.Fix.lambda$new$2(Fix.java:81)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

"Spazio esaurito sul device" = "no space left on device"

**Comment by optyfr** [comment]
Ok lol
Not speaking Italian but « spazio » is enough self speaking (I just did not see the message until then)

**Comment by optyfr** [comment]
So the resolution would be to clean up /tmp and/or extend

**Comment by optyfr** [comment]
Did it work? Or is there another problem here?

**Comment by cinnamonmatexfce** [comment]
> Did it work? Or is there another problem here?

Worked what? Are you referring to your previous message? Should I need to manually extend dedicated space of `/tmp`? Because I always used distro's default settings. Also wouldn't `/tmp` free up space by itself depending on  kernel needs?

**Comment by cinnamonmatexfce** [comment]
> > Did it work? Or is there another problem here?
> 
> Worked what? Are you referring to your previous message? Should I need to manually extend dedicated space of `/tmp`? Because I always used distro's default settings. Also wouldn't `/tmp` free up space by itself depending on  kernel needs?

**Comment by optyfr** [comment]
Most files in /tmp are not from kernels and kernels does not free up anything. At best, a service started by systemd at boot may erase all files, but that’s not mandatory!
/tmp is supposed to be big enough for handling any application needs.
Here you will probably need at least « uncompressed datasize » * « archives processed at the same time »
First thing to do for you is : check if /tmp is freed up at boot, 
secondly : check if data processed does fit your your partition where /tmp reside

**Comment by cinnamonmatexfce** [comment]
Let me do some tests: I'm wondering... What about setting _Adaptive_ mode in JRomManager, rather than messing up with `/tmp`?

**Comment by optyfr** [comment]
...or simply halve the number of threads

**Comment by cinnamonmatexfce** [comment]
OK, found a good tradeoff: 4 (threads) * 4 (7z instances).
In case anyone will find this issue please remember just to **be careful with 7z maximum or even ultra compression**.

---------------------------------------------------------------------------------

P. S.: @optyfr SevenZipJBinding produces files size around ~2  to ~5 MB larger than `7z -mx9`. Is this normal?
Shouldn't solid compression achieve better ratios?
In my case (same identical games):
- 7z solid ULTRA (SevenZipJBinding) = 6248MiB in total
- `7z -ms=off -mx9` (p7zip) = 6157MiB in total
