### ISSUE TITLE
Server Mode: no icons

### ISSUE THREAD

**Issue by docbobo** [optyfr/JRomManager#168]
I was trying out the server mode but I am seeing no icons. Instead, the following exception shows up on the console:

```
2022-06-07 16:01:23.098:WARN:oejs.HttpChannel:qtp681384962-18: /images/icons/script_go.png
java.lang.IllegalArgumentException: URI is not absolute
        at java.base/java.net.URL.fromURI(URL.java:692)
        at java.base/java.net.URI.toURL(URI.java:1116)
        at jrm.server.shared.handlers.ImageServlet.doGet(ImageServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
```

Everything else seems to work as far as I can tell.

**Comment by docbobo** [comment]
Works with 2.4.4

**Comment by optyfr** [comment]
ok it works with 2.4.4 but
- what was the version?
- what was the distribution package used?
- what was operating system?
- what was the call to launch server mode?
- what server mode is it (full or simple)?

**Comment by docbobo** [comment]
For convenience reasons, I've bee building a docker image with the following Dockerfile:

```
FROM alpine:3.16
RUN apk add --no-cache openjdk11 curl

RUN mkdir -p /opt/jrommanager && cd /opt/jrommanager && curl -OL https://github.com/optyfr/JRomManager/releases/download/2.5.1/JRomManager-2.5.1.zip && unzip JRomManager-2.5.1.zip

WORKDIR /opt/jrommanager
ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-cp", "/opt/jrommanager/JRomManager.jar", "jrm.server.Server",  "--client=./webclient", "--workpath=/work"] 
```

The container is then run with

```
docker run -it --rm -v /data/retronas/romimport:/work -p 8080:8080 docbobo/jrommanager:2.5.1
```

Additional info:

```
retronas@retronas:~/docker-jrommanager $ uname -a
Linux retronas 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux
```

When I replace the reference to 2.5.1 with references to 2.4.4 (in the Dockerfile above), then start the container via the same command line, the icons appear and the exceptions disappear.

**Comment by optyfr** [comment]
Interesting… will look into this

**Comment by docbobo** [comment]
Just switched to openjdk17 and the problem seems to be gone...
