### ISSUE TITLE
[Dir updater] cannot perform ADD operations with right-click on beta17

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#255]
`Batch Tools`, `Dir updater`, right-click onto `Src Dirs` sub-window, `Add Src Dirs` is NOT working with [beta-17 (AppImage)](https://github.com/optyfr/JRomManager/releases/download/3.0.0-beta.17/JRomManager-3.0.0-x86_64.AppImage).

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "defdir" is null
        at jrm.merged.module@3.0.0/jrm.fx.ui.BaseController.lambda$chooseDir$2(BaseController.java:37)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
        at jrm.merged.module@3.0.0/jrm.fx.ui.BaseController.chooseDir(BaseController.java:36)
        at jrm.merged.module@3.0.0/jrm.fx.ui.BatchToolsPanelController.lambda$initDat2DirSrc$53(BatchToolsPanelController.java:589)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.controls@21/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
        at javafx.controls@21/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
        at javafx.controls@21/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1368)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
        at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics@21/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
        at javafx.graphics@21/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
        at javafx.graphics@21/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at javafx.graphics@21/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
        at javafx.graphics@21/com.sun.glass.ui.View.notifyMouse(View.java:937)
        at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

This also happens within the `Dst Dirs` sub-window.
```
aused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at javafx.base@21/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
        at javafx.fxml@21/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
        at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1853)
        ... 42 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "defdir" is null
        at jrm.merged.module@3.0.0/jrm.fx.ui.BaseController.chooseOpenFileMulti(BaseController.java:66)
        at jrm.merged.module@3.0.0/jrm.fx.ui.BatchToolsPanelController.onAddDat2DirDstDat(BatchToolsPanelController.java:826)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 49 more
```

------------

`Src Dirs` **only** works with *Drag-and-Drop*.
Adding `Dst Dirs` via *Drag-and-Drop* is NOT working, neither.

**Comment by optyfr** [comment]
> Adding Dst Dirs via Drag-and-Drop is NOT working, neither.

working for me, or probably unrelated, please open another issue (not building a beta release while waiting for more info)

**Comment by cinnamonmatexfce** [comment]
`git clone --recursive https://github.com/optyfr/JRomManager`
`cd JRomManager`
`./gradlew build`

```
$ LC_ALL=C find . -type f -iname "JRomManager*"
./appimage/jrommanager.desktop
./jrmstandalone/build/classes/java/main/jrm/JRomManager.class
./jrmstandalone/build/classes/java/main/jrm/JRomManager$Args.class
./jrmstandalone/build/classes/java/main/jrm/JRomManagerMulti.class
./jrmstandalone/src/main/java/jrm/JRomManager.java
./jrmstandalone/src/main/java/jrm/JRomManagerMulti.java
./jrmfx/build/classes/java/main/jrm/fx/JRomManager.class
./jrmfx/build/classes/java/main/jrm/fx/JRomManager$Args.class
./jrmfx/build/classes/java/main/jrm/fx/JRomManagerMulti.class
./jrmfx/src/main/java/jrm/fx/JRomManager.java
./jrmfx/src/main/java/jrm/fx/JRomManagerMulti.java
./dist/JRomManagerCLI.sh
./dist/JRomManagerServer.bat
./dist/JRomManager.desktop
./dist/JRomManager.ico
./dist/JRomManager.service
./dist/JRomManagerFullServer.sh
./dist/JRomManagerCLI.bat
./dist/full/JRomManager.bat
./dist/full/JRomManager.sh
./dist/JRomManager-multi.sh
./dist/JRomManagerFullServer.bat
./dist/JRomManager.png
./dist/JRomManagerServer.sh
./build/distributions/JRomManager-3.0.0-apidocs.zip
./build/distributions/JRomManager-3.0.0-linux-x64.tar.gz
./build/distributions/JRomManager-3.0.0-nogui-noarch.zip
./build/distributions/jrommanager_3.0.0-1_all.changes
./build/distributions/JRomManager-3.0.0-nogui-noarch.tar.gz
./build/distributions/jrommanager-3.0.0-1.noarch.rpm
./build/distributions/jrommanager_3.0.0-1_all.deb
./build/install/JRomManager-nogui-noarch/JRomManagerCLI.sh
./build/install/JRomManager-nogui-noarch/JRomManagerServer.bat
./build/install/JRomManager-nogui-noarch/JRomManagerFullServer.sh
./build/install/JRomManager-nogui-noarch/JRomManagerCLI.bat
./build/install/JRomManager-nogui-noarch/bin/JRomManager
./build/install/JRomManager-nogui-noarch/bin/JRomManager.bat
./build/install/JRomManager-nogui-noarch/JRomManager.jar
./build/install/JRomManager-nogui-noarch/JRomManager-multi.sh
./build/install/JRomManager-nogui-noarch/JRomManagerFullServer.bat
./build/install/JRomManager-nogui-noarch/lib/JRomManager.jar
./build/install/JRomManager-nogui-noarch/JRomManagerServer.sh
./build/scripts/JRomManager
./build/scripts/JRomManager.bat
./build/libs/JRomManagerCLI-3.0.0.jar
./build/libs/JRomManager.jar
./build/docs/javadoc/jrm/JRomManager.html
./build/docs/javadoc/jrm/cli/JRomManagerCLI.html
./build/docs/javadoc/jrm/JRomManagerMulti.html
./build/docs/javadoc/jrm/fx/JRomManager.html
./build/docs/javadoc/jrm/fx/JRomManagerMulti.html
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$3.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$1.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$RmArgs.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$TrntchkArgs.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$Args.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$MdArgs.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$CompressorArgs.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$DirUpdaterArgs.class
./jrmcli/build/classes/java/main/jrm/cli/JRomManagerCLI$2.class
./jrmcli/src/main/java/jrm/cli/JRomManagerCLI.java
```

Building went fine, all good, but... *How* am I supposed to install (or run) this compiled JRomManager (I'm on ArchLinux)? :blush:

[ sorry for the dumb question... :smiling_face_with_tear: ]


Having a look at [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jrommanager) and there's **NO** `build/image` path:
```
package() {
  cd $srcdir/$_gitname/build/image/JRomManager-linux-x64

  mkdir -p "$pkgdir/usr/share/java/$pkgname/"
  cp -dr --preserve=mode {bin,conf,legal,lib} "$pkgdir/usr/share/java/$pkgname/"

  install -Dm755 $srcdir/$_gitname.sh "$pkgdir/usr/bin/$pkgname"
  install -Dm644 $srcdir/$_gitname.desktop "$pkgdir/usr/share/applications/$_gitname.desktop"
  install -Dm644 $srcdir/$_gitname.png "$pkgdir/usr/share/pixmaps/$_gitname.png"
}
```

**Comment by optyfr** [comment]
Why building? I just wanted more information on what you stated with the beta 17 before doing a release or fixing more, because what I fixed is unrelated with drag&drop and I didn't reproduce it
Appimage is built with the help of GitHub action so it's a bit more complicated than just doing gradle build, there's a few extra script steps

**Comment by optyfr** [comment]
But if you really want to build based on PKGBUILD then follow all steps in it, not just the last one, because it's not simply "gradle build"

**Comment by cinnamonmatexfce** [comment]
> Why building? I just wanted more information on what you stated with the beta 17 before doing a release 

> > Adding Dst Dirs via Drag-and-Drop is NOT working, neither.
> 
> working for me, or probably unrelated, please open another issue (not building a beta release while waiting for more info)


I misunderstood you!!!
I thought you wanted me to try running the latest `master` from git... :upside_down_face:
