### ISSUE TITLE
[Dir updater] "Scr Dats" and "Dst Dirs": cannot perform ADD operations on beta17

### ISSUE THREAD

**Issue by cinnamonmatexfce** [optyfr/JRomManager#256]
Right-click leads to output reported below (for both `Add dat`and `Add Directory` operations).
With *Drag-and-Drop* JRomManager **refuses** adding **.xml* of *folders*
```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1858)
        at javafx.fxml@21/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1726)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.controls@21/javafx.scene.control.MenuItem.fire(MenuItem.java:459)
        at javafx.controls@21/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
        at javafx.controls@21/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1368)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at javafx.base@21/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
        at javafx.base@21/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
        at javafx.base@21/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base@21/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base@21/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base@21/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics@21/javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
        at javafx.graphics@21/javafx.scene.Scene.processMouseEvent(Scene.java:1890)
        at javafx.graphics@21/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at javafx.graphics@21/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at javafx.graphics@21/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
        at javafx.graphics@21/com.sun.glass.ui.View.notifyMouse(View.java:937)
        at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics@21/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:263)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at javafx.base@21/com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
        at javafx.fxml@21/com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
        at javafx.fxml@21/javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1853)
        ... 42 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "defdir" is null
        at jrm.merged.module@3.0.0/jrm.fx.ui.BaseController.lambda$chooseDir$2(BaseController.java:37)
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:198)
        at jrm.merged.module@3.0.0/jrm.fx.ui.BaseController.chooseDir(BaseController.java:36)
        at jrm.merged.module@3.0.0/jrm.fx.ui.BatchToolsPanelController.onAddDat2DirDstDatDir(BatchToolsPanelController.java:835)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 49 more
```

![JRomManager-refuses-](https://github.com/optyfr/JRomManager/assets/65762930/71a6d267-a850-4629-818e-ca1f80018725)

**Comment by optyfr** [comment]
OK, understood... here is the reason why... be ready... it's because grid is empty!!! 🙃 
javafx is a bit dumb with tables controls, to do drag and drop by column (to choose between src dat and dst dirs), I must do it on cell level, except that we need at least one entry created to get the cells filled in the grid control 😕 
So yes, drag and drop doesn't work if we start from an empty grid, not sure I can do more than this, and the only proper solution is to start with context menu (which was buggy indeed in b17). The dirtier solution is to start with an empty entry, but this may introduce a lot more problems than it would resolve

**Comment by cinnamonmatexfce** [comment]
Everything's fine with [beta18](https://github.com/optyfr/JRomManager/releases/tag/3.0.0-beta.18)!!
