### ISSUE TITLE
NIO Exception is preventing fixes from being applied on macos

### ISSUE THREAD

**Issue by tpmoney** [optyfr/JRomManager#271]
In v3.0.2, not all the fixes seemed to be getting applied properly. Looking at the logs I see this:

```        [2024-04-10 22:42:55] [SEVERE] Provider "jar" not found
java.nio.file.ProviderNotFoundException: Provider "jar" not found
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:359)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
        at jrm.merged.module@3.0.0/jrm.profile.fix.actions.OpenContainer.doActionZip(OpenContainer.java:190)
        at jrm.merged.module@3.0.0/jrm.profile.fix.actions.OpenContainer.doAction(OpenContainer.java:107)
        at jrm.merged.module@3.0.0/jrm.profile.fix.Fix.doAction(Fix.java:121)
        at jrm.merged.module@3.0.0/jrm.profile.fix.Fix.lambda$new$2(Fix.java:82)
        at jrm.merged.module@3.0.0/jrm.misc.MultiThreadingVirtual$CallableWith.call(MultiThreadingVirtual.java:229)
        at jrm.merged.module@3.0.0/jrm.misc.MultiThreadingVirtual$CallableWith.call(MultiThreadingVirtual.java:194)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)

[2024-04-10 22:42:55] [WARNING] Action Open Container /userpath/manager-out/roms/cosmccop.zip
        Rename /userpath/manager-out/roms/cosmccop.zip::/cc_d-vo-.ic14 to 8ec06d85-2415-40c8-b015-a032db1143d3_131072.tmp has failed, remaining actions processing will be cancelled
[2024-04-10 22:42:55] [WARNING] Action Open Container /userpath/manager-out/roms/xmultipl.zip
        Rename /userpath/manager-out/roms/xmultipl.zip::/t53.a0,ic50 to 04cbedcb-4940-49b2-982b-ed1c985afc87_131072.tmp has failed, remaining actions processing will be cancelled
[2024-04-10 22:42:55] [WARNING] Missed 2 actions
[2024-04-10 22:42:55] [WARNING] Missed 7 actions
[2024-04-10 22:42:55] [WARNING] Missed 998 actions
[2024-04-10 22:42:55] [WARNING] Missed 2 actions
[2024-04-10 22:42:55] [INFO] Fix total duration for MAME 0.264 (arcade).dat : 00:00:00.147```

**Comment by optyfr** [comment]
fixed in 3f1c259a72c925cc390f40fc901d9a98660af263
