### ISSUE TITLE
Cannot open directories that have files with umlauts in their name

### ISSUE THREAD

**Issue by Snack555** [optyfr/JRomManager#290]
Version: 2.5.1 (Flatpak)

If I have a file with Ä or Ö, and possibly some other characters, JRomManager fails to open the directory. Renaming or moving these files allows me to open the directory again.

I get these error messages in my system log:

```
Exception in thread "Basic L&F File Loading Thread" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/user/Downloads/??
flatpak[221466]:         at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145)
flatpak[221466]:         at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
flatpak[221466]:         at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
flatpak[221466]:         at java.base/java.nio.file.Path.of(Path.java:147)
flatpak[221466]:         at java.base/java.nio.file.Paths.get(Paths.java:69)
flatpak[221466]:         at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(ShellFolder.java:247)
flatpak[221466]:         at java.desktop/javax.swing.filechooser.FileSystemView.getFiles(FileSystemView.java:523)
flatpak[221466]:         at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(BasicDirectoryModel.java:300)
flatpak[221466]:         at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(BasicDirectoryModel.java:289)
flatpak[221466]:         at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by cinnamonmatexfce** [comment]
Please check if bug is still present on latest release.

**Comment by Snack555** [comment]
Ooh, I see, the Flatpak version on Flathub is absolutely ancient if the version numbers are to be believed. I would have thought that it was at least somewhat up to date. Yes, it is indeed working normally if I try the Appimage version (3.0.0) so this is no longer an issue.

However in this case, I'd recommend taking a look at the version distributed on Flathub and deciding what to do with it: https://flathub.org/apps/com.github.optyfr.JRomManager

**Comment by optyfr** [comment]
Hello, 
I think that in that flatpak version the utf-8 for locale may have been missed and it’s only POSIX or C
please see issue #18 to request for a newer version, I think it should be Unicode by default now…
