### ISSUE TITLE
"Fix" Immediately Cancels itself after first round of fixes

### ISSUE THREAD

**Issue by Crono141** [optyfr/JRomManager#89]
Running Latest Beta 2.5.0 (as of writing).  Previous stable version would not parse my dat/xml.

Scanning on Linux.  Scanning remote folder on another machine over the network.  Scan works fine.  Backup works fine.  When it gets to the point of renaming, though, it will pop up a list of files currently being renamed.  The cancel button starts as red, but then turns gray and states (cancelling) almost immediately.  Changes are being made, but only a single "round" per button click.  I have 10k+ files to fix/delete, and I need to keep hitting the "fix" button to get them 5 at a time.  I have verified that the active user has read and write permissions to the remote folder.  Please advise

**Comment by Crono141** [comment]
Follow up.  This appears to be related to the network location that the roms were on.  I did not have the issue when working on local files. You can close this if you like, but I can help troubleshoot the problem if you want to investigate.

**Comment by optyfr** [comment]
Hello, that means that there has been some exceptions thrown while trying to access files/archives, and those exceptions should be visible from .log files in your work folder (typically located at ~/.jrommanager/logs/), It may be related to network reliability problems, or rights to do some operations
Anyway, there will be a new beta release soon (beta 5), lot of things were rewritten since latest beta, this may work better (or not at all)

**Comment by optyfr** [comment]
Did you try with beta 5?

**Comment by Crono141** [comment]
No, sorry. I worked around the issue and have already made the changes to
my library.

**Comment by metafarion** [comment]
I have this problem as well, with v2.5.1, also with files located on a network share.  The fix button only processes one file and then stops.  I did capture some interesting output from the log file though:

```
[2022-10-05 19:54:14] [SEVERE] Cannot invoke "String.substring(int, int)" because the return value of "jrm.profile.data.Entry.getCrc()" is null
java.lang.NullPointerException: Cannot invoke "String.substring(int, int)" because the return value of "jrm.profile.data.Entry.getCrc()" is null
	at jrm.profile.fix.actions.BackupContainer.getFS(BackupContainer.java:94)
	at jrm.profile.fix.actions.BackupContainer.doAction(BackupContainer.java:153)
	at jrm.profile.fix.Fix.doAction(Fix.java:118)
	at jrm.profile.fix.Fix.lambda$new$2(Fix.java:81)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:231)
	at jrm.misc.MultiThreading$CallableWith.call(MultiThreading.java:223)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[2022-10-05 19:54:14] [WARNING] Action jrm.profile.fix.actions.BackupContainer@363c487a has failed, remaining actions processing will be cancelled

```

**Comment by cinnamonmatexfce** [comment]
Mmm...
On my network, FIX operations (on M. A. M. E. sets) work fine with both CIFS (Linux Server --->Windows Client) and NFS (Linux Server ---> Linux Clients) shares.


Have you checked your share settings / permissions?

**Comment by metafarion** [comment]
...hmmm, for some reason it's fine today.
